name: PR Welcome

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: PR Welcome Message
        uses: actions-cool/pr-welcome@v1
        with:
          pr-emoji: '❤️'
